server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:registrationdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    default-encoding: UTF-8
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"

          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000


