

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 2030


spring:
  datasource:
    password: dba245bbd436315
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_1628f5ca24d6750?reconnect=true
    username: b4e0c5c29ea685
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000




